import type { NextPage } from 'next';
import Head from 'next/head';
import { Search, PageTemplate, Dishe } from '@/components';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <PageTemplate>
        <h1>Find delivery options near you</h1>
        <Search />
        <h2>
          Discover your new favorite delivery. Thousands of options at a click.
        </h2>
        <Dishe />
      </PageTemplate>
    </>
  );
};

export default Home;
